### PR TITLE
Add documentation for the ExtrasFormatter class.

### PR DESCRIPTION
**Pull request by kurtwheeler**
I added this feature a long time ago, but I never added anything about it to the docs, so I doubt it's gotten much usage. Finally circling back to do so. Better late than never!

### CODE REVIEW

**Comment by jd** [comment]
pep8 fails

**Comment by jd** [comment]
Can you squash your commits in a single proper one? :)

**Comment by kurtwheeler** [comment]
Is there a preferred method you have for doing so? I generally use the 'Squash and Merge` button in Github. Do you not like it for some reason?

**Comment by jd** [comment]
Yeah, I use [Mergify](https://mergify.io) automerge so I don't bother clicking the button and expect branches to be perfectly organized. ;)

**Comment by kurtwheeler** [comment]
I think this is good to right? Not sure why it's not automerging.

**Comment by jd** [comment]
You force-pushed so my review has been removed :)

**Pull request merged**
